name: api_doc
description: "A new Flutter project that tracks and allows developers to maintain API documentation"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  parse_server_sdk_flutter: ^6.0.0
  http: ^0.13.6
  connectivity_plus: ^3.0.6
  flutter_secure_storage: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

dependency_overrides:
  connectivity_plus:
    path: local_packages/connectivity_plus
